# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('date_interview1', models.CharField(max_length=250)),
                ('date_interview2', models.CharField(max_length=250)),
                ('date_interview3', models.CharField(max_length=250)),
                ('start_internship', models.CharField(max_length=250)),
                ('date_internship', models.CharField(max_length=250)),
            ],
        ),
    ]
